apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hellopod
  name: hellopod
spec:
  containers:
  - image: quay.io/ohthree/spring-test
    name: hellopod
    env:
      - name: MESSAGE_WELCOME
        value: "Hello from Pod Defn"