apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: quay.io/ohthree/spring-test
    name: mypod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
